#spring:
#  profiles:
#    active: local
server:
  port: 8888
spring:
  redis:
    host: 192.168.88.210
    port: 6379
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  main:
    allow-bean-definition-overriding: true
  application:
    name: workspace-service
  datasource:
    url: jdbc:mysql://localhost:3307/db
    username: user
    password: password
    driver-class-name: com.mysql.jdbc.Driver
